-- local nnoremap = require("palani.keymap").nnoremap
--
-- -- dap
-- nnoremap("<leader>db", "<cmd> DapToggleBreakpoint <CR>")
-- nnoremap("<leader>dus", function()
--   local widgets = require('dap.ui.widgets');
--   local sidebar = widgets.sidebar(widgets.scopes);
--   sidebar.open();
-- end
-- )
--
-- -- dap-go
-- nnoremap("<leader>dgt", function()
--   require('dap-go').debug_test()
-- end
-- )
-- nnoremap("<leader>dgl", function()
--   require('dap-go').debug_last()
-- end
-- )

-- -- gopher.nvim
-- nnoremap("<leader>gsj", "<cmd> GoTagAdd json <CR>")
-- nnoremap("<leader>gsy", "<cmd> GoTagAdd yaml <CR>")
