#!/usr/bin/env bash

# ln -s ~/Documents/work/dotfiles.public/.tmux/tmux-sessionizer /usr/local/bin/tmux-sessionizer
if [[ $# -eq 1 ]]; then
    selected=$1
 else
    selected=$(find ~/Documents/work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# 1. First you check if a tmux session exists with a given name.
tmux has-session -t=$selected_name 2> /dev/null

# 2. Create the session if it doesn't exists.
if [[ $? -ne 0 ]]; then
  TMUX='' tmux new-session -d -s "$selected_name" -c "$selected"
fi

# 3. Attach if outside of tmux, switch if you're in tmux.
if [[ -z "$TMUX" ]]; then
  tmux attach -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
